### ISSUE TITLE
Nabu Casa does not work when port is 80

### ISSUE THREAD

**Issue by iainp999** [TekniskSupport/ST-HA-Multi-button-remote#1]
I have found that when using Nabu Casa (my only HTTPS endpoint) the connection fails with a timeout on port 80.

Checking the logs, this is because the app includes the port after the domain in the URL, which Nabu Casa does not respond to.

i.e. issuing a curl POST to `https://<my_url>.nabu.casa:80/api/events/tekhass.button` yields

`curl: (7) Failed to connect to <my_url>.nabu.casa port 80: Operation timed out`

however, issuing the same request to `https://<my_url>.nabu.casa/api/events/tekhass.button` is a success.

would it be possible to leave out the port from the endpoint, either in the case where the port is 80, or alternatively, adjust the app so that the port is optional, and in this case omit it from the endpoint (effectively defaulting to 80)?

**Comment by iainp999** [comment]
FWIW, thanks for the app!  I managed to just hack my copy to remove the port and it works well. 👍

**Comment by TekniskSupport** [comment]
If you just ommit the :80 it will default to 443, as this is the default https port
Doesn't nabu case use https? If so try original code but with port 443 instead, it should work fine

From ST you cannot send webhooks to unencrypted channels, and i don't think that nabu casa listens to  port 80

Great you got it working :)

**Comment by iainp999** [comment]
Doh! My bad, of course. Thanks again for the app!

**Comment by iainp999** [comment]
Closing as I clearly didn't have my thinking cap on :)
